# version: '3.0'
# services:
#   tai-web-fe:
#     image: client
#     build: . # current Dockerfile
#     network_mode: host # ??
#     ports:
#       - "80:80"

version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=opentalk
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - 3306
    networks:
      - back_end
  backend:
    build:
      context: ../server/opentalk
    image: opentalk:latest
    ports:
      - "8080:8080"
    networks:
      - proxy
      - back_end
  nginx:
    image: nginx:1.23.3
    ports:
      - "5173:80"
    volumes:
      - ../Opentalk/dist:/usr/share/nginx/html
      - ./default.config:/etc/nginx/conf.d/default.conf
networks:
  proxy:
    driver: bridge
  back_end:
    driver: bridge
volumes:
  db:
    driver: local
