mail:
  port: '9000'
  hostname: host@mail.com
  from: mailer@mail.com


mail2:
  port: '1000'
  hostname: host2@mail.com
  from: mailer2@mail.com


mail3:
  credentials:
    password: password
    authMethod: SHA1
    username: john
  additionalHeaders:
    secure: 'true'
    redelivery: 'true'
  port: '9000'
  hostname: mailer@mail.com
  from: mailer@mail.com
  defaultRecipients[0]: admin@mail.com
  defaultRecipients[1]: owner@mail.com


##  config with multile file
#
application:
  profiles:
    - dev
    - test
    - prod
    - 3
    - 4
    - 5
#
#spring:
#  profiles:
#    active:
#      - test
#
#
---
#
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
servers:
  - www.abc.test.com
  - www.xyz.test.com

---

spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
servers:
  - www.abc.com
  - www.xyz.com

#---
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#name: ${DEV_NAME:dev-YAML}
#environment: development
#servers:
#  - www.abc.dev.com
#  - www.xyz.dev.com
---
yamlconfig:
  list:
    - item1
    - item2
    - item3
    - item4